# Theme settings
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag

# Site settings
title: Sivamani Vinukonda | Cybersecurity Portfolio
description: "Aspiring SOC Analyst | Cybersecurity Student | Learning Splunk, Python & Cloud Security"
author: Sivamani Vinukonda

# Header navigation
header_pages:
  - index.md
  - about.md
  - projects.md

# Footer content
footer: 'Connect with me on <a href="https://www.linkedin.com/in/sivamanivinukonda/" target="_blank">LinkedIn</a> and <a href="https://github.com/Vinukondashiva" target="_blank">GitHub</a>'

# Style
style: hacker # dark (default), light, hacker, or nord
listen_for_clients_preferred_style: true
